//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int LogID { get; set; }
        public string TableName { get; set; }
        public int RecordID { get; set; }
        public string ChangeType { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangedBy { get; set; }
    
        public virtual Passwords Passwords { get; set; }
    }
}
