//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSchedules
    {
        public int ScheduleID { get; set; }
        public int DoctorID { get; set; }
        public System.DateTime AvailableDateTime { get; set; }
        public bool IsBooked { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
