//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecords
    {
        public int RecordID { get; set; }
        public int PatientID { get; set; }
        public string Diagnosis { get; set; }
        public string Recommendations { get; set; }
        public string TreatmentHistory { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
