//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Program
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        public int PrescriptionID { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public int MedicationID { get; set; }
        public string Dosage { get; set; }
        public string Instructions { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Medications Medications { get; set; }
        public virtual Patients Patients { get; set; }
    }
}
